[project]
name = "tinytracer"
version = "0.1.0"
description = "a tiny path tracer written in python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.5",
    "pillow>=12.0.0",
    "pytest>=9.0.1",
]

[tool.setuptools.packages.find]
where = ["."]
exclude = ["media"]
